// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes.proto

package com.github.cloudgyb.heartchat.modules.server.protocol;

public final class ImMsgProtocols {
    private ImMsgProtocols() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ImSendMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ImSendMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         *
         * @return The id.
         */
        long getId();

        /**
         * <code>string sender = 2;</code>
         *
         * @return The sender.
         */
        java.lang.String getSender();

        /**
         * <code>string sender = 2;</code>
         *
         * @return The bytes for sender.
         */
        com.google.protobuf.ByteString
        getSenderBytes();

        /**
         * <code>string receiver = 3;</code>
         *
         * @return The receiver.
         */
        java.lang.String getReceiver();

        /**
         * <code>string receiver = 3;</code>
         *
         * @return The bytes for receiver.
         */
        com.google.protobuf.ByteString
        getReceiverBytes();

        /**
         * <code>uint32 type = 4;</code>
         *
         * @return The type.
         */
        int getType();

        /**
         * <code>string content = 5;</code>
         *
         * @return The content.
         */
        java.lang.String getContent();

        /**
         * <code>string content = 5;</code>
         *
         * @return The bytes for content.
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <code>uint64 timestamp = 6;</code>
         *
         * @return The timestamp.
         */
        long getTimestamp();
    }

    /**
     * Protobuf type {@code ImSendMsg}
     */
    public static final class ImSendMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ImSendMsg)
            ImSendMsgOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ImSendMsg.newBuilder() to construct.
        private ImSendMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ImSendMsg() {
            sender_ = "";
            receiver_ = "";
            content_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ImSendMsg();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImSendMsg_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImSendMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_ = 0L;

        /**
         * <code>uint64 id = 1;</code>
         *
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
            return id_;
        }

        public static final int SENDER_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object sender_ = "";

        /**
         * <code>string sender = 2;</code>
         *
         * @return The sender.
         */
        @java.lang.Override
        public java.lang.String getSender() {
            java.lang.Object ref = sender_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                sender_ = s;
                return s;
            }
        }

        /**
         * <code>string sender = 2;</code>
         *
         * @return The bytes for sender.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSenderBytes() {
            java.lang.Object ref = sender_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                sender_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RECEIVER_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object receiver_ = "";

        /**
         * <code>string receiver = 3;</code>
         *
         * @return The receiver.
         */
        @java.lang.Override
        public java.lang.String getReceiver() {
            java.lang.Object ref = receiver_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                receiver_ = s;
                return s;
            }
        }

        /**
         * <code>string receiver = 3;</code>
         *
         * @return The bytes for receiver.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getReceiverBytes() {
            java.lang.Object ref = receiver_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                receiver_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 4;
        private int type_ = 0;

        /**
         * <code>uint32 type = 4;</code>
         *
         * @return The type.
         */
        @java.lang.Override
        public int getType() {
            return type_;
        }

        public static final int CONTENT_FIELD_NUMBER = 5;
        @SuppressWarnings("serial")
        private volatile java.lang.Object content_ = "";

        /**
         * <code>string content = 5;</code>
         *
         * @return The content.
         */
        @java.lang.Override
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>string content = 5;</code>
         *
         * @return The bytes for content.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 6;
        private long timestamp_ = 0L;

        /**
         * <code>uint64 timestamp = 6;</code>
         *
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiver_);
            }
            if (type_ != 0) {
                output.writeUInt32(4, type_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(6, timestamp_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiver_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiver_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(4, type_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, timestamp_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg)) {
                return super.equals(obj);
            }
            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg other = (com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg) obj;

            if (getId()
                    != other.getId()) return false;
            if (!getSender()
                    .equals(other.getSender())) return false;
            if (!getReceiver()
                    .equals(other.getReceiver())) return false;
            if (getType()
                    != other.getType()) return false;
            if (!getContent()
                    .equals(other.getContent())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + SENDER_FIELD_NUMBER;
            hash = (53 * hash) + getSender().hashCode();
            hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
            hash = (53 * hash) + getReceiver().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ImSendMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ImSendMsg)
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImSendMsg_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImSendMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.Builder.class);
            }

            // Construct using com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                id_ = 0L;
                sender_ = "";
                receiver_ = "";
                type_ = 0;
                content_ = "";
                timestamp_ = 0L;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImSendMsg_descriptor;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg getDefaultInstanceForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg build() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg buildPartial() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg result = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.id_ = id_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.sender_ = sender_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.receiver_ = receiver_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.type_ = type_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.content_ = content_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.timestamp_ = timestamp_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg) {
                    return mergeFrom((com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg other) {
                if (other == com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getSender().isEmpty()) {
                    sender_ = other.sender_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (!other.getReceiver().isEmpty()) {
                    receiver_ = other.receiver_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                id_ = input.readUInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                sender_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                receiver_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 32: {
                                type_ = input.readUInt32();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 42: {
                                content_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 48: {
                                timestamp_ = input.readUInt64();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 48
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             *
             * @return The id.
             */
            @java.lang.Override
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             *
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(long value) {

                id_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object sender_ = "";

            /**
             * <code>string sender = 2;</code>
             *
             * @return The sender.
             */
            public java.lang.String getSender() {
                java.lang.Object ref = sender_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    sender_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string sender = 2;</code>
             *
             * @return The bytes for sender.
             */
            public com.google.protobuf.ByteString
            getSenderBytes() {
                java.lang.Object ref = sender_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    sender_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string sender = 2;</code>
             *
             * @param value The sender to set.
             * @return This builder for chaining.
             */
            public Builder setSender(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                sender_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string sender = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSender() {
                sender_ = getDefaultInstance().getSender();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string sender = 2;</code>
             *
             * @param value The bytes for sender to set.
             * @return This builder for chaining.
             */
            public Builder setSenderBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                sender_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private java.lang.Object receiver_ = "";

            /**
             * <code>string receiver = 3;</code>
             *
             * @return The receiver.
             */
            public java.lang.String getReceiver() {
                java.lang.Object ref = receiver_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    receiver_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string receiver = 3;</code>
             *
             * @return The bytes for receiver.
             */
            public com.google.protobuf.ByteString
            getReceiverBytes() {
                java.lang.Object ref = receiver_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    receiver_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string receiver = 3;</code>
             *
             * @param value The receiver to set.
             * @return This builder for chaining.
             */
            public Builder setReceiver(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                receiver_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>string receiver = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearReceiver() {
                receiver_ = getDefaultInstance().getReceiver();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>string receiver = 3;</code>
             *
             * @param value The bytes for receiver to set.
             * @return This builder for chaining.
             */
            public Builder setReceiverBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                receiver_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private int type_;

            /**
             * <code>uint32 type = 4;</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public int getType() {
                return type_;
            }

            /**
             * <code>uint32 type = 4;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(int value) {

                type_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 type = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000008);
                type_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <code>string content = 5;</code>
             *
             * @return The content.
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string content = 5;</code>
             *
             * @return The bytes for content.
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string content = 5;</code>
             *
             * @param value The content to set.
             * @return This builder for chaining.
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                content_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>string content = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContent() {
                content_ = getDefaultInstance().getContent();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            /**
             * <code>string content = 5;</code>
             *
             * @param value The bytes for content to set.
             * @return This builder for chaining.
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                content_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            private long timestamp_;

            /**
             * <code>uint64 timestamp = 6;</code>
             *
             * @return The timestamp.
             */
            @java.lang.Override
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>uint64 timestamp = 6;</code>
             *
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 timestamp = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000020);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ImSendMsg)
        }

        // @@protoc_insertion_point(class_scope:ImSendMsg)
        private static final com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg();
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ImSendMsg>
                PARSER = new com.google.protobuf.AbstractParser<ImSendMsg>() {
            @java.lang.Override
            public ImSendMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<ImSendMsg> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ImSendMsg> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImSendMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ImAckMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ImAckMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 msg_id = 1;</code>
         *
         * @return The msgId.
         */
        long getMsgId();

        /**
         * <code>uint32 success = 2;</code>
         *
         * @return The success.
         */
        int getSuccess();

        /**
         * <code>string reason = 3;</code>
         *
         * @return The reason.
         */
        java.lang.String getReason();

        /**
         * <code>string reason = 3;</code>
         *
         * @return The bytes for reason.
         */
        com.google.protobuf.ByteString
        getReasonBytes();

        /**
         * <code>uint64 timestamp = 4;</code>
         *
         * @return The timestamp.
         */
        long getTimestamp();
    }

    /**
     * Protobuf type {@code ImAckMsg}
     */
    public static final class ImAckMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ImAckMsg)
            ImAckMsgOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ImAckMsg.newBuilder() to construct.
        private ImAckMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ImAckMsg() {
            reason_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ImAckMsg();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImAckMsg_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImAckMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.Builder.class);
        }

        public static final int MSG_ID_FIELD_NUMBER = 1;
        private long msgId_ = 0L;

        /**
         * <code>uint64 msg_id = 1;</code>
         *
         * @return The msgId.
         */
        @java.lang.Override
        public long getMsgId() {
            return msgId_;
        }

        public static final int SUCCESS_FIELD_NUMBER = 2;
        private int success_ = 0;

        /**
         * <code>uint32 success = 2;</code>
         *
         * @return The success.
         */
        @java.lang.Override
        public int getSuccess() {
            return success_;
        }

        public static final int REASON_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object reason_ = "";

        /**
         * <code>string reason = 3;</code>
         *
         * @return The reason.
         */
        @java.lang.Override
        public java.lang.String getReason() {
            java.lang.Object ref = reason_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                reason_ = s;
                return s;
            }
        }

        /**
         * <code>string reason = 3;</code>
         *
         * @return The bytes for reason.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getReasonBytes() {
            java.lang.Object ref = reason_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                reason_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 4;
        private long timestamp_ = 0L;

        /**
         * <code>uint64 timestamp = 4;</code>
         *
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (msgId_ != 0L) {
                output.writeUInt64(1, msgId_);
            }
            if (success_ != 0) {
                output.writeUInt32(2, success_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reason_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(4, timestamp_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (msgId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, msgId_);
            }
            if (success_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, success_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reason_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, timestamp_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg)) {
                return super.equals(obj);
            }
            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg other = (com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg) obj;

            if (getMsgId()
                    != other.getMsgId()) return false;
            if (getSuccess()
                    != other.getSuccess()) return false;
            if (!getReason()
                    .equals(other.getReason())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getMsgId());
            hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
            hash = (53 * hash) + getSuccess();
            hash = (37 * hash) + REASON_FIELD_NUMBER;
            hash = (53 * hash) + getReason().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ImAckMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ImAckMsg)
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImAckMsg_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImAckMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.Builder.class);
            }

            // Construct using com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                msgId_ = 0L;
                success_ = 0;
                reason_ = "";
                timestamp_ = 0L;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImAckMsg_descriptor;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg getDefaultInstanceForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg build() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg buildPartial() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg result = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.msgId_ = msgId_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.success_ = success_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.reason_ = reason_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.timestamp_ = timestamp_;
                }
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg) {
                    return mergeFrom((com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg other) {
                if (other == com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg.getDefaultInstance())
                    return this;
                if (other.getMsgId() != 0L) {
                    setMsgId(other.getMsgId());
                }
                if (other.getSuccess() != 0) {
                    setSuccess(other.getSuccess());
                }
                if (!other.getReason().isEmpty()) {
                    reason_ = other.reason_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                msgId_ = input.readUInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 16: {
                                success_ = input.readUInt32();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 26: {
                                reason_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 32: {
                                timestamp_ = input.readUInt64();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private long msgId_;

            /**
             * <code>uint64 msg_id = 1;</code>
             *
             * @return The msgId.
             */
            @java.lang.Override
            public long getMsgId() {
                return msgId_;
            }

            /**
             * <code>uint64 msg_id = 1;</code>
             *
             * @param value The msgId to set.
             * @return This builder for chaining.
             */
            public Builder setMsgId(long value) {

                msgId_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 msg_id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsgId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                msgId_ = 0L;
                onChanged();
                return this;
            }

            private int success_;

            /**
             * <code>uint32 success = 2;</code>
             *
             * @return The success.
             */
            @java.lang.Override
            public int getSuccess() {
                return success_;
            }

            /**
             * <code>uint32 success = 2;</code>
             *
             * @param value The success to set.
             * @return This builder for chaining.
             */
            public Builder setSuccess(int value) {

                success_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 success = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000002);
                success_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object reason_ = "";

            /**
             * <code>string reason = 3;</code>
             *
             * @return The reason.
             */
            public java.lang.String getReason() {
                java.lang.Object ref = reason_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    reason_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string reason = 3;</code>
             *
             * @return The bytes for reason.
             */
            public com.google.protobuf.ByteString
            getReasonBytes() {
                java.lang.Object ref = reason_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    reason_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string reason = 3;</code>
             *
             * @param value The reason to set.
             * @return This builder for chaining.
             */
            public Builder setReason(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reason_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>string reason = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearReason() {
                reason_ = getDefaultInstance().getReason();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>string reason = 3;</code>
             *
             * @param value The bytes for reason to set.
             * @return This builder for chaining.
             */
            public Builder setReasonBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                reason_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private long timestamp_;

            /**
             * <code>uint64 timestamp = 4;</code>
             *
             * @return The timestamp.
             */
            @java.lang.Override
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>uint64 timestamp = 4;</code>
             *
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 timestamp = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000008);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ImAckMsg)
        }

        // @@protoc_insertion_point(class_scope:ImAckMsg)
        private static final com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg();
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ImAckMsg>
                PARSER = new com.google.protobuf.AbstractParser<ImAckMsg>() {
            @java.lang.Override
            public ImAckMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<ImAckMsg> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ImAckMsg> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImAckMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ImSendMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ImSendMsg_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ImAckMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ImAckMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tmes.proto\"k\n\tImSendMsg\022\n\n\002id\030\001 \001(\004\022\016\n\006" +
                        "sender\030\002 \001(\t\022\020\n\010receiver\030\003 \001(\t\022\014\n\004type\030\004" +
                        " \001(\r\022\017\n\007content\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\004" +
                        "\"N\n\010ImAckMsg\022\016\n\006msg_id\030\001 \001(\004\022\017\n\007success\030" +
                        "\002 \001(\r\022\016\n\006reason\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\004" +
                        "BG\n5com.github.cloudgyb.heartchat.module" +
                        "s.server.protocolB\016ImMsgProtocolsb\006proto" +
                        "3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_ImSendMsg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ImSendMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ImSendMsg_descriptor,
                new java.lang.String[]{"Id", "Sender", "Receiver", "Type", "Content", "Timestamp",});
        internal_static_ImAckMsg_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ImAckMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ImAckMsg_descriptor,
                new java.lang.String[]{"MsgId", "Success", "Reason", "Timestamp",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
