// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes.proto

package com.github.cloudgyb.heartchat.modules.server.protocol;

public final class ImMsgProtocols {
    private ImMsgProtocols() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ImMsgOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ImMsg)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint32 id = 1;</code>
         *
         * @return The id.
         */
        int getId();

        /**
         * <code>string content = 2;</code>
         *
         * @return The content.
         */
        java.lang.String getContent();

        /**
         * <code>string content = 2;</code>
         *
         * @return The bytes for content.
         */
        com.google.protobuf.ByteString
        getContentBytes();
    }

    /**
     * Protobuf type {@code ImMsg}
     */
    public static final class ImMsg extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ImMsg)
            ImMsgOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use ImMsg.newBuilder() to construct.
        private ImMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ImMsg() {
            content_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new ImMsg();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImMsg_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImMsg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_ = 0;

        /**
         * <code>uint32 id = 1;</code>
         *
         * @return The id.
         */
        @java.lang.Override
        public int getId() {
            return id_;
        }

        public static final int CONTENT_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object content_ = "";

        /**
         * <code>string content = 2;</code>
         *
         * @return The content.
         */
        @java.lang.Override
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>string content = 2;</code>
         *
         * @return The bytes for content.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeUInt32(1, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, id_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg)) {
                return super.equals(obj);
            }
            com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg other = (com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg) obj;

            if (getId()
                    != other.getId()) return false;
            if (!getContent()
                    .equals(other.getContent())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code ImMsg}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ImMsg)
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsgOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImMsg_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImMsg_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.class, com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.Builder.class);
            }

            // Construct using com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                id_ = 0;
                content_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.internal_static_ImMsg_descriptor;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg getDefaultInstanceForType() {
                return com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.getDefaultInstance();
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg build() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg buildPartial() {
                com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg result = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.id_ = id_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.content_ = content_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg) {
                    return mergeFrom((com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg other) {
                if (other == com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg.getDefaultInstance())
                    return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                id_ = input.readUInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                content_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>uint32 id = 1;</code>
             *
             * @return The id.
             */
            @java.lang.Override
            public int getId() {
                return id_;
            }

            /**
             * <code>uint32 id = 1;</code>
             *
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(int value) {

                id_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 id = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <code>string content = 2;</code>
             *
             * @return The content.
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string content = 2;</code>
             *
             * @return The bytes for content.
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string content = 2;</code>
             *
             * @param value The content to set.
             * @return This builder for chaining.
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                content_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string content = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContent() {
                content_ = getDefaultInstance().getContent();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>string content = 2;</code>
             *
             * @param value The bytes for content to set.
             * @return This builder for chaining.
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                content_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ImMsg)
        }

        // @@protoc_insertion_point(class_scope:ImMsg)
        private static final com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg();
        }

        public static com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ImMsg>
                PARSER = new com.google.protobuf.AbstractParser<ImMsg>() {
            @java.lang.Override
            public ImMsg parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<ImMsg> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ImMsg> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.github.cloudgyb.heartchat.modules.server.protocol.ImMsgProtocols.ImMsg getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ImMsg_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ImMsg_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\tmes.proto\"$\n\005ImMsg\022\n\n\002id\030\001 \001(\r\022\017\n\007cont" +
                        "ent\030\002 \001(\tBG\n5com.github.cloudgyb.heartch" +
                        "at.modules.server.protocolB\016ImMsgProtoco" +
                        "lsb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_ImMsg_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ImMsg_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ImMsg_descriptor,
                new java.lang.String[]{"Id", "Content",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
